{
 "title": "Queue Wait Time Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Request Sender Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request sender endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (type) (custom_http_request_seconds{job=\"requestSender\", quantile=\"0.99\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "App endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (uri) (http_server_requests_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "App Http Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (uri) (http_client_requests_active_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "App Thread Pools Queue Wait Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (name) (executor_idle_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "App Netty Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (executor) (custom_netty_eventloop_lag_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{executor}}"
    }
   ]
  },
  {
   "title": "WebClient Queue Wait Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (name) (custom_web_client_queue_wait_time_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Mongo Commands",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (uri) (mongodb_driver_commands_seconds{job=\"app\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Mongo Netty Event Loop Lag (max)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (executor) (eventLoop_seconds_max{job=\"app\"})",
     "legendFormat": "{{executor}}"
    }
   ]
  },
  {
   "title": "Mongo Netty Event Loop Lag (average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (executor) (rate(eventLoop_seconds_sum{job=\"app\"}[1m])) / sum by (executor) (rate(eventLoop_seconds_count{job=\"app\"}[1m]))",
     "legendFormat": "{{executor}}"
    }
   ]
  }
 ]
}