{
 "title": "Saturation Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Request Sender Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request sender endpoints",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (type) (custom_http_request_seconds{job=\"requestSender\", quantile=\"0.99\"})",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "App Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "App endpoints",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (uri) (http_server_requests_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "App Thread Pools Saturation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (name) (monitored_task_wait_time_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "App Http Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (uri) (http_client_requests_active_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "WebClient Saturation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (name) (custom_web_client_saturation_seconds{job=\"app\", quantile=\"0.99\"})",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}